config/routes.rb
Rails.application.routes.draw do

  get 'sessions/log_in'
  post 'sessions/log_in'
  get 'sessions/log_out'
  get "sign_up" => "authors#new"

  get 'authors/template'
  post 'authors/template'

  get 'authors/redirect'
  post 'authors/redirect'

  resources :authors
  resources :submissions
  resources :surveys

  root 'surveys#index'

end

app/models/submission.rb
class Submission < ActiveRecord::Base
  has_many :responses

  accepts_nested_attributes_for :responses,
      :allow_destroy => true,
      :reject_if     => :all_blank

  def self.new_for_survey(survey_id)
    submission = self.new
    survey = Survey.find(survey_id)
    survey.questions.each do |q|
      submission.responses.build(question: q)
    end
    submission
  end
end

app/controllers/submissions_controller.rb
class SubmissionsController < ApplicationController
  before_action :set_submission, only: [:show, :edit, :update, :destroy]

  # GET /submissions
  # GET /submissions.json
  def index
    @submissions = Submission.all
  end

  # GET /submissions/1
  # GET /submissions/1.json
  def show
  end

  # GET /submissions/new
  def new
    @submission = Submission.new_for_survey(params[:survey_id])
  end

  # GET /submissions/1/edit
  def edit
  end

  # POST /submissions
  # POST /submissions.json
  def create
    @submission = Submission.new(submission_params)

    respond_to do |format|
      if @submission.save
        format.html { redirect_to @submission, notice: 'Submission was successfully created.' }
        format.json { render :show, status: :created, location: @submission }
      else
        format.html { render :new }
        format.json { render json: @submission.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /submissions/1
  # PATCH/PUT /submissions/1.json
  def update
    respond_to do |format|
      if @submission.update(submission_params)
        format.html { redirect_to @submission, notice: 'Submission was successfully updated.' }
        format.json { render :show, status: :ok, location: @submission }
      else
        format.html { render :edit }
        format.json { render json: @submission.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /submissions/1
  # DELETE /submissions/1.json
  def destroy
    @submission.destroy
    respond_to do |format|
      format.html { redirect_to submissions_url, notice: 'Submission was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_submission
      @submission = Submission.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def submission_params
      params.require(:submission).permit(responses_attributes: [:id, :response_text, :question_id, :_destroy])
    end
end

app/helpers/submissions_helper.rb
module SubmissionsHelper
end

app/views/submissions/_form.html.erb
<%= form_for(@submission) do |f| %>
  <% if @submission.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@submission.errors.count, "error") %> prohibited this submission from being saved:</h2>

      <ul>
      <% @submission.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <h3>Survey Questions</h3>

  <%= f.fields_for :responses do |ff| %>
    <%= ff.hidden_field :question_id %>
    <p>
      <%= ff.object.question.question_text %>
      <%= ff.object.question.description %>
      <% if ff.object.question.question_type == "Yes/No" %>
        <%= ff.label :response_text, "Yes", :value => "true"  %>
        <%= ff.radio_button :response_text, true %>
        <%= ff.label :response_text, "No", :value => "false" %>
        <%= ff.radio_button :response_text, false, :checked => true %>
      <% elsif ff.object.question.question_type == "Choice" %>
        <% ff.object.question.options.each do |o| %>
          <%= ff.label :response_text, o.option_text %>
          <%= ff.radio_button :response_text,  :value => o.option_text %>
        <% end %>
      <% elsif ff.object.question.question_type == "Short Answer" %>
        <%= ff.text_field :response_text %>
      <% elsif ff.object.question.question_type == "Long Answer" %>
        <%= ff.text_area :response_text %>
    </p>
      <% end %>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/submissions/edit.html.erb
<h1>Editing Submission</h1>

<%= render 'form' %>

<%= link_to 'Show', @submission %> |
<%= link_to 'Back', submissions_path %>

app/views/submissions/index.html.erb
<h1>Listing Submissions</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @submissions.each do |submission| %>
      <tr>
        <td><%= link_to 'Show', submission %></td>
        <td><%= link_to 'Edit', edit_submission_path(submission) %></td>
        <td><%= link_to 'Destroy', submission, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Submission', new_submission_path %>

app/views/submissions/new.html.erb
<div id="previewWrapper">

  <div class="container">
  <h1 class="newSub">New Submission</h1>

  <%= render 'form' %>

  <%= link_to 'Back', surveys_path %>
  </div>
  
</div>

app/views/submissions/show.html.erb
Thank you for taking this survey!