config/routes.rb
Rails.application.routes.draw do

  get 'sessions/log_in'
  post 'sessions/log_in'
  get 'sessions/log_out'
  get "sign_up" => "authors#new"

  get 'authors/template'
  post 'authors/template'

  get 'authors/redirect'
  post 'authors/redirect'

  resources :authors
  resources :submissions
  resources :surveys

  root 'surveys#index'

end

app/models/survey.rb
class Survey < ActiveRecord::Base
  belongs_to :author
  has_many :questions, dependent: :destroy
  has_many :responses, through: :questions
  has_many :options, through: :questions

  validates :title, presence: true

  accepts_nested_attributes_for :questions,
       :allow_destroy => true,
       :reject_if     => proc { |a| a['question_text'].blank? &&
         a['question_type'].blank? && a['description'].blank? }

  def complete?
    return false if questions.blank?
    return questions.all? do |q|
      q.question_type != "Choice" || q.options.length > 0
    end
  end

  def all_with_author_emails
    joins("LEFT JOIN authors ON surveys.author_id=authors.id").
      select("title, email AS author_email").all
  end
end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
  before_action :set_survey, only: [:show, :edit, :update, :destroy]
  before_action :logged_in?

  # GET /surveys
  # GET /surveys.json
  def index
    @author = Author.find_by_id(session[:author_id])
    @surveys = @author.surveys.order("created_at desc")
  end

  # GET /surveys/1
  # GET /surveys/1.json
  def show
  end

  # GET /surveys/new
  def new
    @survey = Survey.new
    build_questions
  end

  # GET /surveys/1/edit
  def edit
    build_questions
  end

  # POST /surveys
  # POST /surveys.json
  def create
    @survey = Survey.new(survey_params)

    respond_to do |format|
      if @survey.save
        format.html {
          flash[:new]= true
          redirect_to @survey

        }
        format.json { render :show, status: :created, location: @survey }
      else
        format.js { render :new }
        format.json { render json: @survey.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /surveys/1
  # PATCH/PUT /surveys/1.json
  def update
    respond_to do |format|
      if @survey.update(survey_params)
        format.html { redirect_to @survey, notice: 'Survey was successfully updated.' }
        format.json { render :show, status: :ok, location: @survey }
      else
        format.html { render :edit }
        format.json { render json: @survey.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /surveys/1
  # DELETE /surveys/1.json
  def destroy
    @survey.destroy
    redirect_to surveys_path notice: 'Survey was successfully deleted.'
    # respond_to do |format|
    #   format.html { redirect_to surveys_url, notice: 'Survey was successfully destroyed.' }
    #   format.json { head :no_content }
    # end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_survey
      @survey = Survey.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def survey_params
      params.require(:survey).permit(:title, :description, :author_id,
          questions_attributes: [:id, :question_text, :is_required, :description, :question_type, :_destroy,
            options_attributes: [:id, :option_text, :question_id, :_destroy]])
    end

    def build_questions
      if @survey.questions.count < 2
        2.times {@survey.questions.build}
      else
        @survey.questions.build
      end
      2.times {@survey.questions.each { |q| q.options.build }}
    end
end

app/helpers/surveys_helper.rb
module SurveysHelper
end

app/views/surveys/_edit.html.erb
<h1 class="editSurveyH1">Edit Survey</h1>

<%= render 'form' %>

app/views/surveys/_form.html.erb
<div class="formWrapper">
<%= form_for(@survey, remote: true) do |f| %>
  <% if @survey.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@survey.errors.count, "error") %> prohibited this survey from being saved:</h2>

      <ul>
      <% @survey.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field" id="formTitleDiv">
    <%= f.label :title %><br>
    <%= f.text_field( :title, :class => "text") %>
  </div>
  <div class="field" id="formDescDiv">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.hidden_field :author_id, :value => current_user.id %>
  </div>

  <h3>Questions</h3>

  <%= f.fields_for :questions do |ff| %>
    <div class="questions">
      <p>Question Type: <%= ff.select :question_type, ["Yes/No", "Short Answer",
            "Long Answer", "Choice"], :include_blank => true  %></p>
            <p>Required question? <%= ff.check_box :is_required %></p>
      <p>Question: <%= ff.text_field :question_text %></p>
      <p>Question Description: <%= ff.text_area :description %></p>
      <%= ff.fields_for :options do |fff| %>
        <p>Question Option: <%= fff.text_field :option_text %></p>
      <% end %>
    </div>
  <% end %>
  <div class="questionSite"></div>
  <button type="button" class="addQuestion">+ Question</button>

  <div class="actions" id="editButtons">
    <span class="update"><%= f.submit %></span>
    <button class="pure-button" id="cancel">
      <span>Cancel</span>
      <%= link_to 'Back', surveys_path %>
    </button>
<% end %>
  </div>
</div>

app/views/surveys/_new.html.erb
<h1 class="new">New Survey</h1>

<%= render 'form' %>

<%= link_to 'Back', surveys_path %>

app/views/surveys/_show.html.erb
<div class="wrapper">
<header>

  <div class="headerbuttons">
  <button class="pure-button" id="preview">
    <span> Preview </span>
    <%= link_to 'Submission Form', new_submission_path(survey_id: @survey.id) %>
  </button>
  <button class="pure-button" id="edit">
    <span> Edit </span>
  <%= link_to 'Edit', edit_survey_path(@survey), remote: true %>
  </button>
  <button class="pure-button" id="delete">
    <span> Delete </span>
    <%= link_to 'Destroy', @survey, method: :delete, data: { confirm: 'Are you sure?' }, remote: true %>
  </button>
  </div>

<h1 class="surveyTitleHead">
  <%= @survey.title %>
</h1>
<h2>
  <%= @survey.description %>
</h2 class="surveyDescHead">
</header>

<div class="showQuestionDiv">
<% if @survey.complete? %>
  <div class="copyLink">Copy and paste this link: https://surveygoat.herokuapp.com<%= new_submission_path(survey_id: @survey.id) %>
  </div>
<% else %>
  <h3 class="errorMsg"><%= "Surveys must include at least one question, and multiple
      choice questions must have at least two options." %></h3>
<% end %>


<% @survey.questions.each do |q| %>
  <h3>Question: <%= q.question_text %></h3>
  <p>Description: <%= q.description %></p>
  <% q.responses.each do |r| %>
    <p><%= r.response_text %></p>

  <% end  %><br>

<% end  %><br>
</div>

app/views/surveys/_survey.html.erb
  <div class="survey-item pure-g" id="survey-<%= survey.id %>">
    <div class="pure-u-3-4">
    <div class="survey-name"><%= survey.title %></div>
    <div class="survey-desc"><%= survey.description %></div>
    <%= link_to 'Show', survey, remote: true, :class => "survey-link" %>
    </div>
  </div>

app/views/surveys/edit.js.erb
$('#main').html("<%= escape_javascript(render("edit"))%>")

app/views/surveys/index.html.erb
<div id="layout" class="content pure-g">
    <div id="nav" class="pure-u">
      <a href="#" class="nav-menu-button">Menu</a>

        <div class="nav-inner">
          <div class="logo">
            <%= image_tag "empgoatwithtitle.png" %>
          </div>
          <button class="pure-button" id="addSurvey">
            <span>+ Add Survey </span>
            <%= link_to 'New Survey', new_survey_path, remote: true %>
          </button>

          <div class="pure-menu pure-menu-open">
            <ul>
              <li class="userNavInfo">
                <% if current_user %>
                  <span class="welcome">
                    <div>Welcome</div>
                    <span class="user"><%= current_user.name %></span>
                    </span>
                  <div class="logout">
                    <button class="pure-button">
                      <span> Logout </span>
                    <%= link_to "Log out", sessions_log_out_path, :method => "get" %>
                    </button>
                  </div>
                <% end %>
              </li>
            </ul>
          </div>
        </div>
    </div>

  <div id="list" class="pure-u-1">
    <% @surveys.each do |survey| %>
    <%= render partial: 'survey', locals:{ survey:survey } %>
    <% end %>
  </div>

  <div id="main" class="pure-u-1">
      <div class="survey-content"></div>
  </div>
</div>

app/views/surveys/index.js.erb
    var userNav = $("#user_nav").html();
    $('.pure-menu-heading').append(userNav);

app/views/surveys/new.js.erb
$('#main').html("<%= escape_javascript(render("new"))%>")

$(".addQuestion").click(function (){
  var newQuestion = $("#newQuestion").html();
  $('.questionSite').append(newQuestion);
});

app/views/surveys/show.js.erb
// Place all the behaviors and hooks related to the matching controller here.
// All this logic will automatically be available in application.js.
// You can use CoffeeScript in this file: http://coffeescript.org/

// $(function () {
//
//


<% if flash[:new] %>
var newSurvey = $("<%= escape_javascript(render(partial:"survey", locals:{survey:@survey}))%>").hide();
$('#list').prepend(newSurvey);
newSurvey.fadeIn();
<% end %>


$('#survey-<%=@survey.id%>').addClass('active')
if (typeof lastActive !== "undefined") {
  lastActive.removeClass('active');
}
var lastActive = $('#survey-<%=@survey.id%>');

$('#main').html("<%= escape_javascript(render("show"))%>");